# Generated by Django 4.2.5 on 2023-09-15 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_park', '0002_kyc_parking_parking_type_parking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(default='dibas', max_length=50)),
                ('routeId', models.IntegerField()),
                ('bookedSeat', models.CharField(default='', max_length=10)),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('departureLocation', models.CharField(default='Kathmandu', max_length=50)),
                ('destinationLocation', models.CharField(default='Pokhara', max_length=50)),
                ('departureTime', models.TimeField(default='00:00:00')),
                ('arrivalTime', models.TimeField(default='00:00:00')),
                ('departureDate', models.DateField()),
                ('vehicleID', models.CharField(max_length=50)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_park.parking')),
            ],
        ),
    ]
