# Generated by Django 4.2.5 on 2023-09-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='parking',
        ),
        migrations.AddField(
            model_name='ticket',
            name='parking_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
