# Generated by Django 4.2.5 on 2023-09-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_ticket_departurelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
