# Generated by Django 4.2.5 on 2023-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_ticket_departuredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
