# Generated by Django 4.2.5 on 2023-09-16 16:31

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_ticket_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.upload_qr),
        ),
    ]
