# Generated by Django 4.2.5 on 2023-09-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='routeId',
        ),
    ]
