# Generated by Django 4.2.5 on 2023-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_park', '0002_kyc_parking_parking_type_parking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
