# Generated by Django 4.2.5 on 2023-09-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_park', '0003_kyc_address_kyc_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='address',
            field=models.CharField(blank=True, default='Kathmandu', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='name',
            field=models.CharField(blank=True, default='Parking', max_length=255, null=True),
        ),
    ]
